<html>
    <head><title>My first Twig template!</title></head>
    <body>

        <h3>{{ "now"|date(null, "Asia/Kolkata") }}</h3> 


        {% if user.role == 'admin' %}
        <br /><b>Hello, administrator!</b>
        {% elseif user.role == 'user' %}
        <br /><b>Hello, user!</b>
        {% else %}
        <br /><b>You don't have a role defined.</b>
        {% endif %}


        <br />My name is {{ name }}.
        <br />My friends are:
        <ul>
            {% for member in family %}
            <li>{{member.firstname|e}} {{member.lastname|e}}</li>
            {% endfor %}

        </ul>

        {% for i in 0..10 %}
        item number {{ i }}, 
        {% endfor %}

        <br />

        {% for l in 'a'..'z' %}
        {{ l }}, 
        {% endfor %}

        <br />

        {% for k in myarray|keys %}
        <br />key: {{ k }} 
        {% endfor %}

        <br />
        {% for key, val in myarray %}
        <br />key: {{ key }}, val: {{ val }}
        {% else %}
        <br /> no items in the array
        {% endfor %}

        {% for i in range(low=1, high=10, step=2) %}

        <br />{{ i }},
        {% endfor %}

        {% include 'sidebar.html' %}

        {% autoescape %}

        Everything will be automatically escaped in this block (using the HTML strategy)
        {% endautoescape %}




    </body>
</html>

